<script>
	import '../app.css';
	import Small from './../lib/comonents/smallcarta.svelte'
	import Carta from './../lib/comonents/carta.svelte'
	import { DialogOverlay, DialogContent } from 'svelte-accessible-dialog';
    let isOpen;
  const open = () => {
    isOpen = true;
  };

  const close = () => {
    isOpen = false;
	//get name from event timout to show goodby msg
  };
</script>
<DialogOverlay class="over" {isOpen} onDismiss={close}>
	<DialogContent aria-label="form" class="content">
		<div class="tofes" dir="rtl">
<Carta on:close={close}/>
		</div>

	</DialogContent>
	</DialogOverlay >
<div class="ab"> <button on:click={()=>open()}><Small/></button></div>
<slot />

<style>
	.ab{
		position: absolute;
		top: 0;
		left:50%;
		transform : translateX( -50%);
		width :10vw;
		z-index:100;
	}
	.ab:hover{
		animation:blur-out-expand 10.1s linear both
	}
	@keyframes blur-out-expand{0%{transform:scale(1);transform : translateX( -50%);filter:blur(.01px);} 100%{transform:scale(2);transform : translateX( -50%);filter:blur(12px);opacity:0}}
	/* ----------------------------------------------
	animation:blur-out-expand 10.1s linear both
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

@keyframes rotate-bottom{0%{transform:rotate(0);transform-origin:bottom}100%{transform:rotate(360deg);transform-origin:bottom}}
	:global([data-svelte-dialog-content].content) {
    width: 66vw;
  /*  background-image: url(https://res.cloudinary.com/barb1/image/upload/v1642276506/KnittedWool_yuokzt.svg);
    background-position: center center;
    background-size: cover;
	*/
    z-index:222;
    }
	:global([data-svelte-dialog-overlay].over) {
		z-index:222;

	}

</style>