

<script>
  import { onMount } from "svelte";
  import datax from '$lib/data/fruntpage.json'
   let shopsi = datax

  onMount(async () =>{
    shopsi = datax
    fetch(`https://strapi-7iq2.onrender.com/api/categories?populate=%2A`)
  .then(response => response.json())
  .then(data => {
		console.log(data);
    shopsi = data

  }).catch(error => {
    console.log(error);
  })
})
        console.log(shopsi)
import { goto } from "$app/navigation";
import Desc from '$lib/comonents/desctopfront.svelte'
import Mobi from '$lib/comonents/mobilefront.svelte'

let doori = true
	const carouselPhotos = [
		'https://res.cloudinary.com/barb1/image/upload/v1641771584/%D7%91%D7%A8%D7%91%D7%99_4_zvtv3p.gif',
		'https://res.cloudinary.com/barb1/image/upload/v1641771587/%D7%91%D7%A8%D7%91%D7%99_3_srzbj7.gif',
		'https://res.cloudinary.com/barb1/image/upload/v1641771584/%D7%91%D7%A8%D7%91%D7%99_2_owj5x1.gif'
	]
	

	let firstIndex = 0
let i = 0
function categorynext (){
        console.log("click",i)
        if (i + 1 < shopsi.data.length){
                i += 1
        } else{
                i = 0
        }
}
function categoryback (){
        console.log("click",i)
        if (i == 0){
            i = shopsi.data.length - 1              
        } else{
            i -= 1
        }
}
    setInterval(() => {
        if (firstIndex < 4){
  firstIndex = (firstIndex + 1) % carouselPhotos.length
	} else {
         firstIndex = 0
    }
  }, 2700)

  let papistati = "matrix(0.37516528368, 0, 0, 0.360194295645, 653.193664550781, 639.331970214844)"
  let papistati2 = "matrix(0.375165373087, 0, 0, 0.360194295645, 877.636596679688, 639.331970214844)"




</script>


<div class="r">
        <Desc {shopsi}/>
 <!--
<img  src={carouselPhotos[firstIndex]} alt="barbi" title="מזל טוב" />

<button on:click={()=> goto("./rikma")}  class="bg-red-400 bt rounded-full p-2 text-yellow-400 hover:scale-125 hover:bg-yellow-400 hover:text-red-400">להזמנת רקמה</button>
-->
</div>
<div class="mb">
        <div class="grid">
<Mobi {shopsi}/>
        </div>
</div>
<style>
.r{
    display: none;    
}
.mb{
        display:unset;
        height: 100vh;
        width: 100vw;
        justify-content: center;
        align-items: center;
        background-color: #ff83a8;
    }
    .grid{
        display:grid;
        height: 100vh;
        width: 100vw;
        justify-content: center;
        align-items: center;
        background-color: #ff83a8;
    }
@media (min-width: 650px){        
    .r{
        display:unset;
        height: 100vh;
        width: 100vw;
        display: grid;
        justify-content: center;
        align-items: center;
        background-color: #ff83a8;
    }
    .mb{
        display:none;
    }
}
    .bt{
      position: absolute;
      left: 50%;
      transform: translate(-50%,-50%);
      top: 90%;
    }
 
    /* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
----------------------------------------------

.doori:hover{animation:wobble-horizontal-bottom 5s linear both}
 @keyframes wobble-horizontal-bottom{0%,100%{transform:translateX(0);transform-origin:50% 50%}15%{transform:translateX(-30px) rotate(-6deg)}30%{transform:translateX(15px) rotate(6deg)}45%{transform:translateX(-15px) rotate(-3.6deg)}60%{transform:translateX(9px) rotate(2.4deg)}75%{transform:translateX(-6px) rotate(-1.2deg)}}
 *//* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.wobble-horizontal-bottom{animation:wobble-horizontal-bottom .8s linear both} @keyframes wobble-horizontal-bottom{0%,100%{transform:translateX(0);transform-origin:50% 50%}15%{transform:translateX(-30px) rotate(-6deg)}30%{transform:translateX(15px) rotate(6deg)}45%{transform:translateX(-15px) rotate(-3.6deg)}60%{transform:translateX(9px) rotate(2.4deg)}75%{transform:translateX(-6px) rotate(-1.2deg)}}
</style>